const renderSignature = (label, signature, box) => {
  const imageMarkup = signature
    ? `<img src="${signature}" alt="${label}" style="width:100%;height:100%;object-fit:contain;" />`
    : `<div style="font-size:12px;color:#4b5563;text-align:center;">${label}</div>`;

  return `<div style="position:absolute;left:${box.x}px;top:${box.y}px;width:${box.width}px;height:${box.height}px;border:1px dashed #94a3b8;border-radius:12px;background:rgba(255,255,255,0.86);display:flex;align-items:center;justify-content:center;overflow:hidden;">${imageMarkup}</div>`;
};

export const buildFinalDocumentHtml = ({ request, student, faculty, hod, facultySignature, hodSignature }) => `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${request.title}</title>
    <style>
      body { margin:0; font-family: Arial, sans-serif; background:#eef2ff; color:#0f172a; }
      .sheet { width:900px; margin:32px auto; background:#fff; border-radius:24px; box-shadow:0 20px 60px rgba(15,23,42,.16); overflow:hidden; }
      .header { padding:24px 32px; background:linear-gradient(135deg,#0f172a,#1d4ed8); color:#fff; }
      .meta { display:grid; grid-template-columns:repeat(2,1fr); gap:12px; padding:20px 32px; background:#f8fafc; font-size:14px; }
      .document { position:relative; min-height:900px; margin:24px 32px 32px; padding:32px; border:1px solid #e2e8f0; border-radius:24px; background:linear-gradient(180deg,#ffffff 0%,#f8fbff 100%); }
      .content { white-space:pre-wrap; line-height:1.8; font-size:16px; }
      .footer { padding:20px 32px 32px; font-size:13px; color:#475569; }
    </style>
  </head>
  <body>
    <div class="sheet">
      <div class="header">
        <h1 style="margin:0 0 6px;">Document Approval System</h1>
        <div>${request.title}</div>
      </div>
      <div class="meta">
        <div><strong>Student:</strong> ${student.name} (${student.rollNo})</div>
        <div><strong>Department:</strong> ${student.department}</div>
        <div><strong>Faculty:</strong> ${faculty.name}</div>
        <div><strong>HOD:</strong> ${hod.name}</div>
        <div><strong>Request Type:</strong> ${request.type}</div>
        <div><strong>Status:</strong> Completed / Signed</div>
      </div>
      <div class="document">
        <div class="content">${request.content || "Attached document submitted by student."}</div>
        ${renderSignature("Faculty Signature", facultySignature, request.facultySignatureBox)}
        ${renderSignature("HOD Signature", hodSignature, request.hodSignatureBox)}
      </div>
      <div class="footer">Generated by DigitalFlow on ${new Date().toLocaleString()}.</div>
    </div>
  </body>
</html>`;
